# .goreleaser.yaml

# 配置 GoReleaser 的版本
version: 1
# 配置构建时的环境
env:
  - CGO_ENABLED=0
  - GO111MODULE=on

# 配置构建和发布信息
builds:
  - main: ./
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # 可以根据需要添加其他构建配置

# 发布配置
release:
  # 发布到 GitHub
  github:
    owner: xgd16
    name_template: "{{ .Name }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    # 可以在这里添加其他 GitHub 相关的配置，比如 release_notes、changelog、draft 等

# 构建产物的设置
archives:
  - name_template: "{{ .Name }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    files:
      - dist/*
    format: tar.gz
    # 可以添加其他构建产物的配置

# 指定构建产物的生成目录
dist: dist
